### ISSUE TITLE
1.5.0 of androidx.test:orchestrator causes all of cucumber tests to fail

### ISSUE THREAD

**Issue by johngray1965** [cucumber/cucumber-android#130]
### 👓 What did you see?

the androidx.test:orchestrator seems to crash on the cucumber tests.   I can see in logcat that seems to go through the motions for each test, but doesn't seem like they are actually run.   In the end, it says that no tests were run.

When I moved back to 1.4.2, everything runs again.   Non-cucumber tests are working with 1.5.0.

### ✅ What did you expect to see?

I expect the tests to run

### 📦 Which tool/library version are you using?

io.cucumber:cucumber-android:7.14.0
io.cucumber:cucumber-android-hilt:7.14.0

### 🔬 How could we reproduce it?

Android cucumber tests with androidx.test:orchestrator 1.5.0, and androidx.test.services:test-services 1.5.0

Everything works with 1.4.2, nothing works with 1.5.0

**Comment by rkrishnan2012** [comment]
This is caused by https://github.com/android/android-test/issues/2255

**Comment by lsuski** [comment]
Try adding `useFileNameCompatibleName = true` to your `@CucumberOptions`

**Comment by volic** [comment]
@lsuski  I can easily reproduce it with `useFileNameCompatibleName = true`. Cucumber tests do not work for me with the orchestrator.

**Comment by volic** [comment]
I finally solved the issue. The error happened by running a `gcloud` command for the firebase test lab with spaces.
In the past gcloud supported spaces like that
`gcloud beta firebase test android run --app APP_APK --device model=NexusLowRes,orientation=landscape`
Cuurently, with orchestrator 1.5.0. it started failing.
The fix is changing `  ` to `=`
`gcloud beta firebase test android run --app=APP_APK --device=model=NexusLowRes,orientation=landscape`
