### ISSUE TITLE
Are there any plans to update to the newer versions of cucumber?

### ISSUE THREAD

**Issue by MolochKel** [cucumber/cucumber-android#68]
Hi, I was wondering if you were planning to update the dependencies to the current version. Cucumber-jvm is on version 6.x now, while cucumber-android is dependent on 4.x
I tried to use the current cucumber-jvm with an android emulator, but was unsuccessful.
Thanks.

**Comment by lsuski** [comment]
Are there any concrete features in new cucumber you would like to have? Currently I don't have much time for updating to newest cucumber-java because there is no such need from my as developer, my company and clients perspective and they are main sponsors of this repository. However I'm open to rethink this if there are some significant improvements and/or it will not require days of work for me which I don't have now

**Comment by MolochKel** [comment]
Thank you for the reply. :)
We are currently considering using cucumber-android for test execution in our project. The question is more generic, as we are factoring in how current the project is and what the future outlook is like.
As far as new features/changes go, I consider most of the ones I'm interested in nice-to-haves rather than needed.

**Comment by mpkorstanje** [comment]
If you do decide to use the project you and your compangy should consider contributing too it as well. This could include upgrading to newer versions of Cucumber. It will guarantee continuity of the project for as long as you are using it.

**Comment by lsuski** [comment]
From my perspective I'm quite happy with this set of features I have in cucumber-android because this is mainly gherkin parser, steps executor and table to class mapper - everything else I try to achieve independently of cucumber or any framework through kotlin extensions. If this migration will take 1-2 days maybe I could find time in this year for it :). It is in my roadmap of course but has low priority.

**Comment by mpkorstanje** [comment]
I wasn't questioning your priorities or time commitment. However I believe you are currently the only maintainer. So if you one day decide to stop supporting this project, like the core team did once then some one else will have to pick up. So it would be in MolochKels best interest to contribute to avoid just that situation. Aside from being good open-source citizenship of-course.

**Comment by MolochKel** [comment]
I agree that the core features are there and most of what newer versions offer is useful, but not something we can't reproduce without it.
If we do end up using cucumber-android, I would definitely see it as being in my/our best interest to contribute to the project as well. Might be under similar time constraints as Isuski, but it is a possibility.

**Comment by lsuski** [comment]
@mpkorstanje sure, my answear was mainly to @MolochKel. I'm not going to leave this project as long as I develop on Android and cucumber-android is currently heavily used by many projects in my company so for us is just like other internal library (but open sourced one) and will be maintained as long as it is needed.

**Comment by lsuski** [comment]
Currently the main issues I faced with cucumber-java 6.x is that `ClassLoader` works differently on Android and it does not return classes in method `getResources` which is extensively used in `cucumber-java`. 
Another minor problem (I hope) is usage of classes which are not available in Android SDK but available in standard JDK 8

**Comment by mpkorstanje** [comment]
@lsuski reminded me about this class loader problem in the future. I think we can design the internal APIs to have a layer that doesn't need the class loader.
